services:
  app:
    image: elnapoli/domotica:1.0.0
    container_name: app-container
    volumes:
      - /home/elnapoli/domotica/mis_tareas:/app/tasks
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"  # Para acceso a los pines GPIO (si es necesario)
      - "/dev/mem:/dev/mem"            # Si es necesario para acceso directo a memoria

